[package]
name = "nostale_crypto_rs"
version = "0.1.0"
authors = ["Roman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
encoding = "0.2.33"